name: buildmate
description: "Buildmate - Your Ultimate Construction Companion"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.3
  skeletonizer: ^2.1.0+1
  fluttertoast: ^9.0.0
  font_awesome_flutter: ^10.10.0
  image_picker: 1.2.0
  animations: ^2.1.0
  cached_network_image: ^3.3.1
  connectivity_plus: ^7.0.0
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700